### ISSUE TITLE
Sharing the Raw Data

### ISSUE THREAD

**Issue by elhamazd** [happy-fish-01/National_interest_waiver_waittime#1]
Thank you so much for putting this together. This is very helpful. We are trying to raise our concerns about the long processing time at the TSC and it would be very helpful if you could share the raw data that you used for making this plot. Would it be possible for you to add that?
Thank you so much!

**Comment by happy-fish-01** [comment]
Good suggestion. I hope this could bring to attention the long wait applicants have to endure. I will work on that right away.
