### ISSUE TITLE
Happy to help

### ISSUE THREAD

**Issue by BGroever** [happy-fish-01/National_interest_waiver_waittime#2]
Hi,

Love your chart I am happy to help. How often do you update it?

**Comment by happy-fish-01** [comment]
Usually as soon as Chen updates their website I update mine. So it really depends on them.

**Comment by BGroever** [comment]
ok, let me know if you need any help entering the data, after tracking my case daily, I decided to do it once a week now, but I am happy to enter some data on the weekend if it helps you out

**Comment by happy-fish-01** [comment]
Thank you. If I get overwhelmed I'll let you know.
