### ISSUE TITLE
how do you get the csvs for NIW cases?

### ISSUE THREAD

**Issue by mpuri1** [happy-fish-01/National_interest_waiver_waittime#3]
this is a great tool and I've been tracking my case for about a year now (LINxx :-(   ). I wanted to ask how are you getting data in csv format? On the website I see a mix of case approvals between O-1, Eb-1 and EB-2 without a dedicated place for EB2 cases.

**Comment by happy-fish-01** [comment]
Hi mpuri14:

I use Google Vision to scan the documents automatically. After Google Vision recognizes the words and symbols of the PDFs, I can easily download the data in CSV form. Once that's done, separating NIW cases from the rest is fairly straight-forward.

Does this answer your question?

**Comment by mpuri1** [comment]
that is really cool. would you mind including your codebase in your next update?

**Comment by happy-fish-01** [comment]
Hi mpuri14: I'm not ready to do that yet.
