### ISSUE TITLE
Does the data include premium processing or not?

### ISSUE THREAD

**Issue by yagmurbbayraktar** [happy-fish-01/National_interest_waiver_waittime#4]
Most of the cases seem to be approved within 30 days since Feb 24. Is it because these are premium cases? If so, why not the data from previous months do not include those?

**Comment by mrhoseinian** [comment]
I believe it does include pp

**Comment by happy-fish-01** [comment]
The I-140 approval forms make no distinction on this issue. However, we can infer from the bimodal distribution of the wait times in recent months that, yes PP are included.
